language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  xctool -project RRiOSApp/RRiOSApp.xcodeproj -scheme RRiOSApp -sdk iphonesimulator7.0 build test -freshInstall -freshSimulator

