language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -workspace refuge-ios/refuge-ios.xcodeproj -scheme refuge-ios -sdk iphonesimulator8.1
