language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -workspace RRiOSApp/RRiOSApp.xcworkspace -scheme RRiOSApp -sdk iphonesimulator8.0
