language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -workspace RefugeRestrooms/RefugeRestrooms.xcodeproj -scheme RefugeRestrooms -sdk iphonesimulator8.1
