language: objective-c
before_install:
  - brew unlink xctool
  - brew update
  - brew install xctool

script:
  - xctool test -workspace RRiOSApp/RRiOSApp.xcworkspace -scheme RRiOSApp -sdk iphonesimulator8.1
