language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
  - xctool test -project refuge-ios/refuge-ios.xcodeproj -scheme refuge-ios -sdk iphonesimulator7.0
